// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::engine::protocol::RequestRegistration`.

pub mod add_raster;
pub mod add_void;
pub mod layer_tree;

use crate::engine::protocol::RequestRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<RequestRegistration> {
    vec![
        add_raster::register(),
        add_void::register(),
        layer_tree::register(),
    ]
}
