// @generated by build.rs — do not edit manually.
// To add request kinds, create or edit a domain .rs file in this
// directory that exports `pub fn registrations() -> Vec<crate::engine::protocol::RequestRegistration>`.

pub mod brush_graph;
pub mod brush_library;
pub mod brush_preview;
pub mod clipboard;
pub mod color_pick;
pub mod document;
pub mod floating;
pub mod history;
pub mod image_io;
pub mod layer_props;
pub mod layers;
pub mod mask;
pub mod overlay;
pub mod painting;
pub mod preview;
pub mod preview_config;
pub mod registry_types;
pub mod selection;
pub mod stroke;
pub mod veils;
pub mod view;

use crate::engine::protocol::RequestRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<RequestRegistration> {
    let mut all = Vec::new();
    all.extend(brush_graph::registrations());
    all.extend(brush_library::registrations());
    all.extend(brush_preview::registrations());
    all.extend(clipboard::registrations());
    all.extend(color_pick::registrations());
    all.extend(document::registrations());
    all.extend(floating::registrations());
    all.extend(history::registrations());
    all.extend(image_io::registrations());
    all.extend(layer_props::registrations());
    all.extend(layers::registrations());
    all.extend(mask::registrations());
    all.extend(overlay::registrations());
    all.extend(painting::registrations());
    all.extend(preview::registrations());
    all.extend(preview_config::registrations());
    all.extend(registry_types::registrations());
    all.extend(selection::registrations());
    all.extend(stroke::registrations());
    all.extend(veils::registrations());
    all.extend(view::registrations());
    all
}
