coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

comment:
  layout: "diff, files"
  require_changes: true

ignore:
  - "crates/darkly/build.rs"
  - "**/test_utils.rs"
  - "frontend/**"
