//! Node-graph composable brush engine.
//!
//! Phase 8: Stamp tips + user-exposed properties.

pub mod builtin_presets;
pub mod brush_tip;
pub mod curve_math;
pub mod dab_pool;
pub mod eval;
pub mod gpu_context;
pub mod interpolation;
pub mod nodes;
pub mod paint_info;
pub mod pipelines;
pub mod preset;
pub mod preset_library;
pub mod spacing;
pub mod stroke_engine;
pub mod wire;

use std::collections::HashMap;

use crate::nodegraph::NodeRegistration;
use wire::BrushWireType;

/// Type alias used by `build.rs` auto-generation for the nodes directory.
pub type BrushNodeRegistration = NodeRegistration<BrushWireType>;

/// HashMap-backed registry of all brush node types.
///
/// Populated from `nodes::registrations()` (auto-generated by `build.rs`).
/// This holds **static metadata** — port definitions, parameter schemas,
/// display names — used by the compiler and the UI.  It does *not* hold
/// evaluator logic; that lives in `default_evaluators()` as a separate
/// map of `type_id → Box<dyn BrushNodeEvaluator>`.  The split exists
/// because metadata is data (serializable, cloneable, needed at compile
/// time) while evaluators are behavior (trait objects, needed at runtime).
pub struct BrushNodeRegistry {
    map: HashMap<String, BrushNodeRegistration>,
}

impl BrushNodeRegistry {
    /// Build the registry from the auto-discovered node modules.
    pub fn new() -> Self {
        let regs = nodes::registrations();
        let mut map = HashMap::with_capacity(regs.len());
        for reg in regs {
            map.insert(reg.type_id.to_string(), reg);
        }
        Self { map }
    }

    /// Look up a node registration by type_id.
    pub fn get(&self, type_id: &str) -> Option<&BrushNodeRegistration> {
        self.map.get(type_id)
    }

    /// All registered node types.
    pub fn types(&self) -> impl Iterator<Item = &BrushNodeRegistration> {
        self.map.values()
    }

    /// The backing HashMap (for passing to the compiler).
    pub fn as_map(&self) -> &HashMap<String, BrushNodeRegistration> {
        &self.map
    }
}

impl Default for BrushNodeRegistry {
    fn default() -> Self {
        Self::new()
    }
}

/// Create the standard set of evaluators for all built-in nodes.
///
/// Separate from `BrushNodeRegistry` because evaluators are trait objects
/// (runtime behavior) while the registry holds static metadata (compile-
/// time port/param schemas).  Both are keyed by the same `type_id` string.
/// The runner takes ownership of the evaluator map and uses it during
/// `execute_cpu()` and `execute_gpu()` to dispatch each node's computation.
pub fn default_evaluators() -> HashMap<String, Box<dyn eval::BrushNodeEvaluator>> {
    let mut map: HashMap<String, Box<dyn eval::BrushNodeEvaluator>> = HashMap::new();
    // CPU nodes.
    map.insert("pen_input".into(), Box::new(nodes::pen_input::PenInputEvaluator));
    map.insert("constant".into(), Box::new(nodes::constant::ConstantEvaluator));
    map.insert("multiply".into(), Box::new(nodes::multiply::MultiplyEvaluator));
    map.insert("curve".into(), Box::new(nodes::curve::CurveEvaluator));
    map.insert("paint_color".into(), Box::new(nodes::paint_color::PaintColorEvaluator));
    map.insert("add".into(), Box::new(nodes::add::AddEvaluator));
    map.insert("clamp".into(), Box::new(nodes::clamp::ClampEvaluator));
    map.insert("remap".into(), Box::new(nodes::remap::RemapEvaluator));
    map.insert("mix".into(), Box::new(nodes::mix::MixEvaluator));
    map.insert("split_vec2".into(), Box::new(nodes::split_vec2::SplitVec2Evaluator));
    map.insert("make_color".into(), Box::new(nodes::make_color::MakeColorEvaluator));
    map.insert("user_input".into(), Box::new(nodes::user_input::UserInputEvaluator));
    // GPU nodes.
    map.insert("circle".into(), Box::new(nodes::circle::CircleEvaluator));
    map.insert("image".into(), Box::new(nodes::image::ImageEvaluator));
    map.insert("stamp".into(), Box::new(nodes::stamp::StampEvaluator));
    map.insert("color_output".into(), Box::new(nodes::color_output::ColorOutputEvaluator));
    map
}

/// Build the default brush graph: pressure-sensitive dab painting.
///
/// Graph topology:
///   circle ──texture──→     stamp.tip
///   pen_input ──pressure──→ stamp.size
///   paint_color ──color──→  stamp.color
///   stamp ──dab──→          color_output.dab
///   stamp ──dab_size──→     color_output.dab_size
///   stamp ──scatter_offset──→ color_output.scatter_offset
///   pen_input ──position──→ color_output.position
///
/// Produces a basic round brush with pressure → size dynamics.
pub fn default_graph() -> crate::nodegraph::Graph<BrushWireType> {
    use crate::nodegraph::{Graph, PortRef};

    let registry = BrushNodeRegistry::new();
    let mut graph = Graph::new();

    let pen_reg = registry.get("pen_input").unwrap();
    let pen = graph.add_node("pen_input", pen_reg.ports.clone(), vec![]);
    graph.nodes.get_mut(&pen).unwrap().position = [40.0, 40.0];

    let color_reg = registry.get("paint_color").unwrap();
    let paint_color = graph.add_node("paint_color", color_reg.ports.clone(), vec![]);
    graph.nodes.get_mut(&paint_color).unwrap().position = [40.0, 200.0];

    let circle_reg = registry.get("circle").unwrap();
    let circle = graph.add_node("circle", circle_reg.ports.clone(), vec![]);
    graph.nodes.get_mut(&circle).unwrap().position = [40.0, 360.0];

    let stamp_reg = registry.get("stamp").unwrap();
    let stamp = graph.add_node("stamp", stamp_reg.ports.clone(), vec![]);
    graph.nodes.get_mut(&stamp).unwrap().position = [280.0, 40.0];

    let out_reg = registry.get("color_output").unwrap();
    let color_output = graph.add_node("color_output", out_reg.ports.clone(), vec![]);
    graph.nodes.get_mut(&color_output).unwrap().position = [520.0, 40.0];

    // circle.texture → stamp.tip
    graph.connect(
        PortRef { node: circle, port: "texture".into() },
        PortRef { node: stamp, port: "tip".into() },
    ).unwrap();

    // pressure → stamp.size
    graph.connect(
        PortRef { node: pen, port: "pressure".into() },
        PortRef { node: stamp, port: "size".into() },
    ).unwrap();

    // paint_color → stamp.color
    graph.connect(
        PortRef { node: paint_color, port: "color".into() },
        PortRef { node: stamp, port: "color".into() },
    ).unwrap();

    // stamp.dab → color_output.dab
    graph.connect(
        PortRef { node: stamp, port: "dab".into() },
        PortRef { node: color_output, port: "dab".into() },
    ).unwrap();

    // stamp.dab_size → color_output.dab_size
    graph.connect(
        PortRef { node: stamp, port: "dab_size".into() },
        PortRef { node: color_output, port: "dab_size".into() },
    ).unwrap();

    // pen_input.position → color_output.position
    graph.connect(
        PortRef { node: pen, port: "position".into() },
        PortRef { node: color_output, port: "position".into() },
    ).unwrap();

    // stamp.scatter_offset → color_output.scatter_offset
    graph.connect(
        PortRef { node: stamp, port: "scatter_offset".into() },
        PortRef { node: color_output, port: "scatter_offset".into() },
    ).unwrap();

    graph
}

/// Compile any brush graph into a ready-to-run runner.
pub fn compile_graph(
    graph: &crate::nodegraph::Graph<BrushWireType>,
) -> Result<eval::BrushGraphRunner, crate::nodegraph::GraphError> {
    let registry = BrushNodeRegistry::new();
    let evaluators = default_evaluators();
    eval::BrushGraphRunner::new(graph, registry.as_map(), evaluators)
}

/// Compile the default brush graph into a ready-to-run runner.
pub fn default_runner() -> Result<eval::BrushGraphRunner, crate::nodegraph::GraphError> {
    compile_graph(&default_graph())
}

/// Deserialize a brush graph from JSON and compile it.
///
/// Returns the compiled runner or a human-readable error string.
pub fn compile_from_json(json: &str) -> Result<eval::BrushGraphRunner, String> {
    let graph: crate::nodegraph::Graph<BrushWireType> =
        serde_json::from_str(json).map_err(|e| format!("invalid graph JSON: {e}"))?;
    compile_graph(&graph).map_err(|e| format!("graph compilation failed: {e}"))
}

/// Validate a brush graph from JSON without compiling.
///
/// Returns Ok(()) or a human-readable error string.
pub fn validate_graph_json(json: &str) -> Result<(), String> {
    let graph: crate::nodegraph::Graph<BrushWireType> =
        serde_json::from_str(json).map_err(|e| format!("invalid graph JSON: {e}"))?;
    let registry = BrushNodeRegistry::new();
    crate::nodegraph::compile(&graph, registry.as_map())
        .map_err(|e| format!("graph validation failed: {e}"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gpu::params::ParamValue;
    use crate::nodegraph::{Graph, NodeId, PortRef};
    use super::eval::BrushGraphRunner;
    use super::paint_info::{PaintInformation, StrokeRecord};
    use super::wire::{BrushWireType, ScalarValue};

    /// Helper: build a graph with pen_input → multiply(constant 0.5) on pressure.
    fn pressure_times_half_graph() -> (Graph<BrushWireType>, NodeId, NodeId, NodeId) {
        let registry = BrushNodeRegistry::new();
        let mut graph = Graph::new();

        // Add pen_input node.
        let pen_reg = registry.get("pen_input").unwrap();
        let pen = graph.add_node("pen_input", pen_reg.ports.clone(), vec![]);

        // Add constant(0.5) node.
        let const_reg = registry.get("constant").unwrap();
        let constant = graph.add_node(
            "constant",
            const_reg.ports.clone(),
            vec![ParamValue::Float(0.5)],
        );

        // Add multiply node.
        let mul_reg = registry.get("multiply").unwrap();
        let multiply = graph.add_node("multiply", mul_reg.ports.clone(), vec![]);

        // Wire: pen_input.pressure → multiply.a
        graph.connect(
            PortRef { node: pen, port: "pressure".into() },
            PortRef { node: multiply, port: "a".into() },
        ).unwrap();

        // Wire: constant.value → multiply.b
        graph.connect(
            PortRef { node: constant, port: "value".into() },
            PortRef { node: multiply, port: "b".into() },
        ).unwrap();

        (graph, pen, constant, multiply)
    }

    #[test]
    fn pressure_times_constant() {
        let (graph, _pen, _constant, multiply) = pressure_times_half_graph();
        let registry = BrushNodeRegistry::new();
        let evaluators = default_evaluators();

        let mut runner = BrushGraphRunner::new(&graph, registry.as_map(), evaluators).unwrap();

        // Evaluate with pressure = 0.8.
        let info = PaintInformation {
            pressure: 0.8,
            ..Default::default()
        };
        runner.seed_sensors(&info, [0.0, 0.0, 0.0, 1.0]);
        runner.execute_cpu();

        // multiply.result should be 0.8 * 0.5 = 0.4.
        let slot = runner.find_node_output_slot(multiply, "result").unwrap();
        let result = runner.read_slot(slot).unwrap();
        match result {
            ScalarValue::Scalar(v) => assert!((v - 0.4).abs() < 1e-6, "expected 0.4, got {v}"),
            other => panic!("expected Scalar, got {:?}", other),
        }
    }

    #[test]
    fn curve_spline_identity() {
        let registry = BrushNodeRegistry::new();
        let mut graph = Graph::new();

        let pen_reg = registry.get("pen_input").unwrap();
        let pen = graph.add_node("pen_input", pen_reg.ports.clone(), vec![]);

        // Default identity curve: [(0,0), (1,1)] → output ≈ input
        let curve_reg = registry.get("curve").unwrap();
        let curve = graph.add_node(
            "curve",
            curve_reg.ports.clone(),
            vec![ParamValue::Curve(vec![[0.0, 0.0], [1.0, 1.0]])],
        );

        graph.connect(
            PortRef { node: pen, port: "pressure".into() },
            PortRef { node: curve, port: "input".into() },
        ).unwrap();

        let evaluators = default_evaluators();
        let mut runner = BrushGraphRunner::new(&graph, registry.as_map(), evaluators).unwrap();

        let info = PaintInformation {
            pressure: 0.5,
            ..Default::default()
        };
        runner.seed_sensors(&info, [0.0, 0.0, 0.0, 1.0]);
        runner.execute_cpu();

        let slot = runner.find_node_output_slot(curve, "output").unwrap();
        let result = runner.read_slot(slot).unwrap();
        match result {
            ScalarValue::Scalar(v) => {
                assert!((v - 0.5).abs() < 0.02, "identity curve at 0.5: got {v}");
            }
            other => panic!("expected Scalar, got {:?}", other),
        }
    }

    #[test]
    fn curve_spline_s_curve() {
        let registry = BrushNodeRegistry::new();
        let mut graph = Graph::new();

        let pen_reg = registry.get("pen_input").unwrap();
        let pen = graph.add_node("pen_input", pen_reg.ports.clone(), vec![]);

        // S-curve: compress low values
        let curve_reg = registry.get("curve").unwrap();
        let curve = graph.add_node(
            "curve",
            curve_reg.ports.clone(),
            vec![ParamValue::Curve(vec![[0.0, 0.0], [0.5, 0.2], [1.0, 1.0]])],
        );

        graph.connect(
            PortRef { node: pen, port: "pressure".into() },
            PortRef { node: curve, port: "input".into() },
        ).unwrap();

        let evaluators = default_evaluators();
        let mut runner = BrushGraphRunner::new(&graph, registry.as_map(), evaluators).unwrap();

        let info = PaintInformation {
            pressure: 0.5,
            ..Default::default()
        };
        runner.seed_sensors(&info, [0.0, 0.0, 0.0, 1.0]);
        runner.execute_cpu();

        let slot = runner.find_node_output_slot(curve, "output").unwrap();
        let result = runner.read_slot(slot).unwrap();
        match result {
            ScalarValue::Scalar(v) => {
                assert!((v - 0.2).abs() < 0.05, "s-curve at 0.5: expected ~0.2, got {v}");
            }
            other => panic!("expected Scalar, got {:?}", other),
        }
    }

    #[test]
    fn stroke_record_accumulates() {
        let mut record = StrokeRecord::new([1.0, 0.0, 0.0, 1.0], "test_brush".into());
        assert!(record.is_empty());

        for i in 0..10 {
            record.push(PaintInformation {
                pos: [i as f32 * 10.0, 50.0],
                pressure: 0.5 + (i as f32) * 0.05,
                index: i,
                ..Default::default()
            });
        }

        assert_eq!(record.len(), 10);
        assert_eq!(record.events[0].index, 0);
        assert_eq!(record.events[9].index, 9);
        assert!((record.events[0].pressure - 0.5).abs() < 1e-6);
    }

    #[test]
    fn disconnected_input_uses_default() {
        // multiply with no wires — both inputs should use their defaults (1.0).
        let registry = BrushNodeRegistry::new();
        let mut graph = Graph::new();

        let mul_reg = registry.get("multiply").unwrap();
        let multiply = graph.add_node("multiply", mul_reg.ports.clone(), vec![]);

        let evaluators = default_evaluators();
        let mut runner = BrushGraphRunner::new(&graph, registry.as_map(), evaluators).unwrap();

        runner.execute_cpu();

        let slot = runner.find_node_output_slot(multiply, "result").unwrap();
        let result = runner.read_slot(slot).unwrap();
        match result {
            ScalarValue::Scalar(v) => {
                assert!((v - 1.0).abs() < 1e-6, "expected 1.0 (default * default), got {v}");
            }
            other => panic!("expected Scalar, got {:?}", other),
        }
    }

    #[test]
    fn paint_color_output() {
        let registry = BrushNodeRegistry::new();
        let mut graph = Graph::new();

        let color_reg = registry.get("paint_color").unwrap();
        let color_node = graph.add_node("paint_color", color_reg.ports.clone(), vec![]);

        let evaluators = default_evaluators();
        let mut runner = BrushGraphRunner::new(&graph, registry.as_map(), evaluators).unwrap();

        let fg_color = [1.0, 0.2, 0.3, 1.0];
        let info = PaintInformation::default();
        runner.seed_sensors(&info, fg_color);
        runner.execute_cpu();

        let slot = runner.find_node_output_slot(color_node, "color").unwrap();
        let result = runner.read_slot(slot).unwrap();
        match result {
            ScalarValue::Color(c) => assert_eq!(c, fg_color),
            other => panic!("expected Color, got {:?}", other),
        }
    }

    #[test]
    fn default_runner_compiles() {
        let runner = super::default_runner();
        assert!(runner.is_ok(), "default_runner() failed: {:?}", runner.err());
    }
}
