//! Node-graph composable brush engine.

pub mod brush_tip;
pub mod builtin_brushes;
pub mod bundle;
pub mod checkpoint_ring;
pub mod composite_pipeline;
pub mod curve_math;
pub mod dab_pool;
pub mod eval;
pub mod gpu_context;
pub mod import;
pub mod interpolation;
pub mod library;
pub mod node;
pub mod nodes;
pub mod paint_info;
pub mod paint_target_ext;
pub mod pipeline;
pub mod preview_renderer;
pub mod preview_subgraph;
pub mod save_points;
pub mod scratch;
pub mod spacing;
pub mod stabilizer;
pub mod stabilizers;
pub mod state;
pub mod stroke_buffer;
pub mod stroke_engine;
pub mod wgsl_compile;
pub mod wire;

use std::collections::HashMap;

use crate::nodegraph::NodeRegistration;
use wire::BrushWireType;

/// Reference dab dimension (width = height), in canvas pixels — the
/// UI/UX convention that defines what `brush size = 1.0` means in
/// canvas-pixel terms. Used by:
///
/// - `stamp`: the rendered dab's longer axis at `effective_size = 1.0`
///   is `DAB_REFERENCE_SIZE` canvas pixels (the slider's "100%" mark).
/// - `liquify`: `radius = size * DAB_REFERENCE_SIZE * 0.5`.
/// - `paint_compiled` / `watercolor_compiled`: same `effective_size *
///   DAB_REFERENCE_SIZE / 2` formula for `effective_radius`.
/// - `StrokeEngine::default_diameter() = DAB_REFERENCE_SIZE * 0.5` —
///   spacing fallback before any dab has reported its own size.
///
/// **Not a hard cap on dab footprint.** `effective_size` (= `size_input
/// × size`) can exceed 1.0 unbounded — both the slider and any wired
/// sensor (pen pressure, random, ...) can push past 100%. The system
/// must tolerate dab footprints arbitrarily larger than this value.
///
/// If you need a hard cap on something, introduce a separately-named
/// constant. Do not repurpose this one.
pub const DAB_REFERENCE_SIZE: u32 = 512;

/// Wrapper around `NodeRegistration<BrushWireType>` carrying the GPU
/// pipelines a brush node owns.  Used by `build.rs` auto-generation for
/// the nodes directory.
pub use node::BrushNodeRegistration;

/// HashMap-backed registry of all brush node types.
///
/// Populated from `nodes::registrations()` (auto-generated by `build.rs`).
/// This holds **static metadata** — port definitions, parameter schemas,
/// display names — used by the compiler and the UI.  It does *not* hold
/// evaluator logic; that lives in `default_evaluators()` as a separate
/// map of `type_id → Box<dyn BrushNodeEvaluator>`.  The split exists
/// because metadata is data (serializable, cloneable, needed at compile
/// time) while evaluators are behavior (trait objects, needed at runtime).
///
/// Stores a `BrushNodeRegistration` wrapper per type plus a parallel
/// `nodegraph_map` of just the bare `NodeRegistration<W>` for handing to
/// the nodegraph compiler, which is generic over `W` and doesn't know
/// about the brush-specific pipeline metadata.
pub struct BrushNodeRegistry {
    map: HashMap<String, BrushNodeRegistration>,
    nodegraph_map: HashMap<String, NodeRegistration<BrushWireType>>,
}

impl BrushNodeRegistry {
    /// Build the registry from the auto-discovered node modules.
    pub fn new() -> Self {
        let regs = nodes::registrations();
        let mut map = HashMap::with_capacity(regs.len());
        let mut nodegraph_map = HashMap::with_capacity(regs.len());
        for reg in regs {
            let type_id = reg.node.type_id.to_string();
            nodegraph_map.insert(type_id.clone(), reg.node.clone());
            map.insert(type_id, reg);
        }
        Self { map, nodegraph_map }
    }

    /// Look up a node registration by type_id.
    pub fn get(&self, type_id: &str) -> Option<&BrushNodeRegistration> {
        self.map.get(type_id)
    }

    /// All registered node types.
    pub fn types(&self) -> impl Iterator<Item = &BrushNodeRegistration> {
        self.map.values()
    }

    /// The bare `NodeRegistration<W>` map for the nodegraph compiler
    /// (which is generic over `W` and doesn't carry brush-specific
    /// pipeline metadata).
    pub fn as_map(&self) -> &HashMap<String, NodeRegistration<BrushWireType>> {
        &self.nodegraph_map
    }
}

impl Default for BrushNodeRegistry {
    fn default() -> Self {
        Self::new()
    }
}

/// Create the standard set of evaluators for all built-in nodes.
///
/// Separate from `BrushNodeRegistry` because evaluators are trait objects
/// (runtime behavior) while the registry holds static metadata (compile-
/// time port/param schemas).  Both are keyed by the same `type_id` string.
/// The runner takes ownership of the evaluator map and uses it during
/// `execute_cpu()` and `execute_gpu()` to dispatch each node's computation.
pub fn default_evaluators() -> HashMap<String, Box<dyn eval::BrushNodeEvaluator>> {
    let mut map: HashMap<String, Box<dyn eval::BrushNodeEvaluator>> = HashMap::new();
    // CPU nodes.
    map.insert(
        "pen_input".into(),
        Box::new(nodes::pen_input::PenInputEvaluator),
    );
    map.insert(
        "multiply".into(),
        Box::new(nodes::multiply::MultiplyEvaluator),
    );
    map.insert("curve".into(), Box::new(nodes::curve::CurveEvaluator));
    map.insert(
        "paint_color".into(),
        Box::new(nodes::paint_color::PaintColorEvaluator),
    );
    map.insert("add".into(), Box::new(nodes::add::AddEvaluator));
    map.insert("clamp".into(), Box::new(nodes::clamp::ClampEvaluator));
    map.insert("remap".into(), Box::new(nodes::remap::RemapEvaluator));
    map.insert("mix".into(), Box::new(nodes::mix::MixEvaluator));
    map.insert(
        "split_vec2".into(),
        Box::new(nodes::split_vec2::SplitVec2Evaluator),
    );
    map.insert(
        "make_color".into(),
        Box::new(nodes::make_color::MakeColorEvaluator),
    );
    map.insert("random".into(), Box::new(nodes::random::RandomEvaluator));
    map.insert("jitter".into(), Box::new(nodes::jitter::JitterEvaluator));
    map.insert("scatter".into(), Box::new(nodes::scatter::ScatterEvaluator));
    // GPU nodes.
    map.insert("circle".into(), Box::new(nodes::circle::CircleEvaluator));
    map.insert("image".into(), Box::new(nodes::image::ImageEvaluator));
    map.insert("stamp".into(), Box::new(nodes::stamp::StampEvaluator));
    map.insert(
        "paint_compiled".into(),
        Box::new(nodes::paint_compiled::PaintCompiledEvaluator),
    );
    map.insert(
        "texture_overlay".into(),
        Box::new(nodes::texture_overlay::TextureOverlayEvaluator),
    );
    map.insert("liquify".into(), Box::new(nodes::liquify::LiquifyEvaluator));
    map.insert(
        "watercolor_compiled".into(),
        Box::new(nodes::watercolor_compiled::WatercolorCompiledEvaluator),
    );
    map.insert("smudge".into(), Box::new(nodes::smudge::SmudgeEvaluator));
    // Internal terminal used by per-node preview pipeline. Not exposed to the
    // frontend palette (filtered by `category == "internal"`).
    map.insert(
        "preview_terminal".into(),
        Box::new(nodes::preview_terminal::PreviewTerminalEvaluator),
    );
    map
}

/// Build the default brush graph: pressure-sensitive disc through the
/// compiled `paint_compiled` terminal. Same shape as Round in
/// [`builtin_brushes`] — `pen → paint_color → circle (sine, amplitude 0)
/// → stamp → paint_compiled` — minus the per-brush configuration
/// closure (no exposed softness, no flow wire).
pub fn default_graph() -> crate::nodegraph::Graph<BrushWireType> {
    use crate::gpu::params::ParamValue;
    use crate::nodegraph::{Graph, PortRef};

    let registry = BrushNodeRegistry::new();
    let mut graph = Graph::new();

    let pen = graph.add_node(
        "pen_input",
        registry.get("pen_input").unwrap().ports.clone(),
        vec![],
    );
    let paint_color = graph.add_node(
        "paint_color",
        registry.get("paint_color").unwrap().ports.clone(),
        vec![],
    );
    let circle = graph.add_node(
        "circle",
        registry.get("circle").unwrap().ports.clone(),
        vec![ParamValue::Int(0)], // sine, amplitude 0 → plain disc
    );
    let stamp = graph.add_node(
        "stamp",
        registry.get("stamp").unwrap().ports.clone(),
        vec![ParamValue::Int(0)], // AlphaMask
    );
    let terminal = graph.add_node(
        "paint_compiled",
        registry.get("paint_compiled").unwrap().ports.clone(),
        vec![],
    );

    let wires = [
        (pen, "pressure", stamp, "size_input"),
        (pen, "pressure", stamp, "flow"),
        (paint_color, "color", stamp, "color"),
        (circle, "texture", stamp, "tip"),
        (stamp, "dab", terminal, "rgba"),
        (pen, "position", terminal, "position"),
    ];
    for (fnode, fport, tnode, tport) in wires {
        graph
            .connect(
                PortRef {
                    node: fnode,
                    port: fport.into(),
                },
                PortRef {
                    node: tnode,
                    port: tport.into(),
                },
            )
            .unwrap();
    }

    graph
}

/// Compile any brush graph into a ready-to-run runner.
///
/// If the graph terminates in a `paint_compiled` node, this also
/// generates the per-brush WGSL fragment shader and attaches it to
/// the runner. Brush load fails (with a string-form `GraphError`-ish
/// error coerced via `panic!` ⇒ TODO) when any upstream node lacks a
/// `compile_wgsl` implementation. Brushes that terminate in any other
/// terminal (`paint`, `color_output`, `watercolor_batched`, …) take
/// the per-dab dispatch path unchanged.
pub fn compile_graph(
    graph: &crate::nodegraph::Graph<BrushWireType>,
) -> Result<eval::BrushGraphRunner, crate::nodegraph::GraphError> {
    let registry = BrushNodeRegistry::new();
    let evaluators = default_evaluators();
    let mut runner = eval::BrushGraphRunner::new(graph, registry.as_map(), evaluators)?;
    if graph
        .nodes
        .values()
        .any(|n| eval::is_compiled_terminal(&n.type_id))
    {
        let plan = crate::nodegraph::compile(graph, registry.as_map())?;
        // Build a fresh evaluators map for the compiler — the runner
        // owns the live one. Cheap (just trait-object constructors).
        let compile_evals = default_evaluators();
        let compiled =
            wgsl_compile::compile_brush_to_wgsl(graph, &plan, &compile_evals).map_err(|e| {
                // Surface the WGSL compile error as a Graph compile
                // error so the engine's existing error path handles
                // it. Detail goes through `Display`.
                eprintln!("paint_compiled WGSL compilation failed: {e}");
                crate::nodegraph::GraphError::CycleDetected
            })?;
        runner.set_compiled_brush(std::sync::Arc::new(compiled));
    }
    Ok(runner)
}

/// Compile the default brush graph into a ready-to-run runner.
pub fn default_runner() -> Result<eval::BrushGraphRunner, crate::nodegraph::GraphError> {
    compile_graph(&default_graph())
}

/// Deserialize a brush graph from JSON and compile it.
///
/// Returns the compiled runner or a human-readable error string.
pub fn compile_from_json(json: &str) -> Result<eval::BrushGraphRunner, String> {
    let graph: crate::nodegraph::Graph<BrushWireType> =
        serde_json::from_str(json).map_err(|e| format!("invalid graph JSON: {e}"))?;
    compile_graph(&graph).map_err(|e| format!("graph compilation failed: {e}"))
}

/// Reset every exposed input port on every node back to its registration
/// default. This produces a "canonical" view of the graph that's
/// independent of any user-facing scrubs (size, opacity, hardness, etc.).
///
/// Used by the active-dab thumbnail render so the brush icon represents
/// the brush's identity (shape, texture, dynamics) rather than the user's
/// momentary parameter adjustments. Generalizes per-port pinning so adding
/// a new exposed scrub (opacity hotkey, hardness hotkey, …) requires no
/// changes here.
///
/// Ports flagged with [`crate::nodegraph::PortDef::persist_in_thumbnail`]
/// are exempt — orientation knobs (rotation, phase) visibly change the
/// dab itself, so the icon should reflect them.
pub fn reset_exposed_scrubs(graph: &mut crate::nodegraph::Graph<BrushWireType>) {
    let registry = BrushNodeRegistry::new();
    let mut resets: Vec<(crate::nodegraph::NodeId, String, f32)> = Vec::new();
    for (id, node) in &graph.nodes {
        let Some(reg) = registry.get(&node.type_id) else {
            continue;
        };
        for port in &reg.ports {
            if port.exposed
                && port.dir == crate::nodegraph::PortDir::Input
                && !port.persist_in_thumbnail
            {
                resets.push((*id, port.name.clone(), port.default));
            }
        }
    }
    for (id, name, default) in resets {
        let _ = graph.set_port_default(id, &name, default);
    }
}

/// Validate a brush graph from JSON without compiling.
///
/// Returns Ok(()) or a human-readable error string.
pub fn validate_graph_json(json: &str) -> Result<(), String> {
    let graph: crate::nodegraph::Graph<BrushWireType> =
        serde_json::from_str(json).map_err(|e| format!("invalid graph JSON: {e}"))?;
    let registry = BrushNodeRegistry::new();
    crate::nodegraph::compile(&graph, registry.as_map())
        .map_err(|e| format!("graph validation failed: {e}"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::eval::BrushGraphRunner;
    use super::paint_info::{PaintInformation, StrokeRecord};
    use super::wire::{BrushWireType, ScalarValue};
    use super::*;
    use crate::gpu::params::ParamValue;
    use crate::nodegraph::{Graph, NodeId, PortRef};

    /// Helper: build a graph with pen_input.pressure → multiply.a,
    /// and multiply.b pinned to 0.5 via a port default (no extra node).
    fn pressure_times_half_graph() -> (Graph<BrushWireType>, NodeId, NodeId) {
        let registry = BrushNodeRegistry::new();
        let mut graph = Graph::new();

        let pen_reg = registry.get("pen_input").unwrap();
        let pen = graph.add_node("pen_input", pen_reg.ports.clone(), vec![]);

        let mul_reg = registry.get("multiply").unwrap();
        let multiply = graph.add_node("multiply", mul_reg.ports.clone(), vec![]);

        // pen.pressure → multiply.a
        graph
            .connect(
                PortRef {
                    node: pen,
                    port: "pressure".into(),
                },
                PortRef {
                    node: multiply,
                    port: "a".into(),
                },
            )
            .unwrap();

        // multiply.b defaults to 0.5 — no wire, just a port default.
        graph.set_port_default(multiply, "b", 0.5).unwrap();

        (graph, pen, multiply)
    }

    #[test]
    fn pressure_times_port_default() {
        let (graph, _pen, multiply) = pressure_times_half_graph();
        let registry = BrushNodeRegistry::new();
        let evaluators = default_evaluators();

        let mut runner = BrushGraphRunner::new(&graph, registry.as_map(), evaluators).unwrap();

        // Evaluate with pressure = 0.8.
        let info = PaintInformation {
            pressure: 0.8,
            ..Default::default()
        };
        runner.seed_sensors(&info, [0.0, 0.0, 0.0, 1.0], 42, 0);
        runner.execute_cpu();

        // multiply.result should be 0.8 * 0.5 = 0.4.
        let slot = runner.find_node_output_slot(multiply, "result").unwrap();
        let result = runner.read_slot(slot).unwrap();
        match result {
            ScalarValue::Scalar(v) => assert!((v - 0.4).abs() < 1e-6, "expected 0.4, got {v}"),
            other => panic!("expected Scalar, got {:?}", other),
        }
    }

    #[test]
    fn curve_spline_identity() {
        let registry = BrushNodeRegistry::new();
        let mut graph = Graph::new();

        let pen_reg = registry.get("pen_input").unwrap();
        let pen = graph.add_node("pen_input", pen_reg.ports.clone(), vec![]);

        // Default identity curve: [(0,0), (1,1)] → output ≈ input
        let curve_reg = registry.get("curve").unwrap();
        let curve = graph.add_node(
            "curve",
            curve_reg.ports.clone(),
            vec![ParamValue::Curve(vec![[0.0, 0.0], [1.0, 1.0]])],
        );

        graph
            .connect(
                PortRef {
                    node: pen,
                    port: "pressure".into(),
                },
                PortRef {
                    node: curve,
                    port: "input".into(),
                },
            )
            .unwrap();

        let evaluators = default_evaluators();
        let mut runner = BrushGraphRunner::new(&graph, registry.as_map(), evaluators).unwrap();

        let info = PaintInformation {
            pressure: 0.5,
            ..Default::default()
        };
        runner.seed_sensors(&info, [0.0, 0.0, 0.0, 1.0], 42, 0);
        runner.execute_cpu();

        let slot = runner.find_node_output_slot(curve, "output").unwrap();
        let result = runner.read_slot(slot).unwrap();
        match result {
            ScalarValue::Scalar(v) => {
                assert!((v - 0.5).abs() < 0.02, "identity curve at 0.5: got {v}");
            }
            other => panic!("expected Scalar, got {:?}", other),
        }
    }

    #[test]
    fn curve_spline_s_curve() {
        let registry = BrushNodeRegistry::new();
        let mut graph = Graph::new();

        let pen_reg = registry.get("pen_input").unwrap();
        let pen = graph.add_node("pen_input", pen_reg.ports.clone(), vec![]);

        // S-curve: compress low values
        let curve_reg = registry.get("curve").unwrap();
        let curve = graph.add_node(
            "curve",
            curve_reg.ports.clone(),
            vec![ParamValue::Curve(vec![[0.0, 0.0], [0.5, 0.2], [1.0, 1.0]])],
        );

        graph
            .connect(
                PortRef {
                    node: pen,
                    port: "pressure".into(),
                },
                PortRef {
                    node: curve,
                    port: "input".into(),
                },
            )
            .unwrap();

        let evaluators = default_evaluators();
        let mut runner = BrushGraphRunner::new(&graph, registry.as_map(), evaluators).unwrap();

        let info = PaintInformation {
            pressure: 0.5,
            ..Default::default()
        };
        runner.seed_sensors(&info, [0.0, 0.0, 0.0, 1.0], 42, 0);
        runner.execute_cpu();

        let slot = runner.find_node_output_slot(curve, "output").unwrap();
        let result = runner.read_slot(slot).unwrap();
        match result {
            ScalarValue::Scalar(v) => {
                assert!(
                    (v - 0.2).abs() < 0.05,
                    "s-curve at 0.5: expected ~0.2, got {v}"
                );
            }
            other => panic!("expected Scalar, got {:?}", other),
        }
    }

    #[test]
    fn stroke_record_accumulates() {
        let mut record = StrokeRecord::new([1.0, 0.0, 0.0, 1.0], "test_brush".into());
        assert!(record.is_empty());

        for i in 0..10 {
            record.push(PaintInformation {
                pos: [i as f32 * 10.0, 50.0],
                pressure: 0.5 + (i as f32) * 0.05,
                index: i,
                ..Default::default()
            });
        }

        assert_eq!(record.len(), 10);
        assert_eq!(record.events[0].index, 0);
        assert_eq!(record.events[9].index, 9);
        assert!((record.events[0].pressure - 0.5).abs() < 1e-6);
    }

    #[test]
    fn disconnected_input_uses_default() {
        // multiply with no wires — both inputs should use their defaults (1.0).
        let registry = BrushNodeRegistry::new();
        let mut graph = Graph::new();

        let mul_reg = registry.get("multiply").unwrap();
        let multiply = graph.add_node("multiply", mul_reg.ports.clone(), vec![]);

        let evaluators = default_evaluators();
        let mut runner = BrushGraphRunner::new(&graph, registry.as_map(), evaluators).unwrap();

        runner.execute_cpu();

        let slot = runner.find_node_output_slot(multiply, "result").unwrap();
        let result = runner.read_slot(slot).unwrap();
        match result {
            ScalarValue::Scalar(v) => {
                assert!(
                    (v - 1.0).abs() < 1e-6,
                    "expected 1.0 (default * default), got {v}"
                );
            }
            other => panic!("expected Scalar, got {:?}", other),
        }
    }

    #[test]
    fn paint_color_output() {
        let registry = BrushNodeRegistry::new();
        let mut graph = Graph::new();

        let color_reg = registry.get("paint_color").unwrap();
        let color_node = graph.add_node("paint_color", color_reg.ports.clone(), vec![]);

        let evaluators = default_evaluators();
        let mut runner = BrushGraphRunner::new(&graph, registry.as_map(), evaluators).unwrap();

        let fg_color = [1.0, 0.2, 0.3, 1.0];
        let info = PaintInformation::default();
        runner.seed_sensors(&info, fg_color, 42, 0);
        runner.execute_cpu();

        let slot = runner.find_node_output_slot(color_node, "color").unwrap();
        let result = runner.read_slot(slot).unwrap();
        match result {
            ScalarValue::Color(c) => assert_eq!(c, fg_color),
            other => panic!("expected Color, got {:?}", other),
        }
    }

    #[test]
    fn default_runner_compiles() {
        let runner = super::default_runner();
        assert!(
            runner.is_ok(),
            "default_runner() failed: {:?}",
            runner.err()
        );
    }

    /// Jitter passes `input` through unchanged when `amount` is zero, and
    /// stays inside `[input - amount, input + amount]` otherwise.
    /// Two jitter nodes in the same graph produce independent streams.
    #[test]
    fn jitter_bounds_and_independence() {
        let registry = BrushNodeRegistry::new();
        let mut graph = Graph::new();

        let pen = graph.add_node(
            "pen_input",
            registry.get("pen_input").unwrap().ports.clone(),
            vec![],
        );
        let jit_a = graph.add_node(
            "jitter",
            registry.get("jitter").unwrap().ports.clone(),
            vec![],
        );
        let jit_b = graph.add_node(
            "jitter",
            registry.get("jitter").unwrap().ports.clone(),
            vec![],
        );

        // A: pressure → input, amount=0 (default). Should pass through.
        graph
            .connect(
                PortRef {
                    node: pen,
                    port: "pressure".into(),
                },
                PortRef {
                    node: jit_a,
                    port: "input".into(),
                },
            )
            .unwrap();

        // B: pressure → input, amount=0.25 via port default.
        graph
            .connect(
                PortRef {
                    node: pen,
                    port: "pressure".into(),
                },
                PortRef {
                    node: jit_b,
                    port: "input".into(),
                },
            )
            .unwrap();
        graph.set_port_default(jit_b, "amount", 0.25).unwrap();

        let evaluators = default_evaluators();
        let mut runner = BrushGraphRunner::new(&graph, registry.as_map(), evaluators).unwrap();

        let slot_a = runner.find_node_output_slot(jit_a, "value").unwrap();
        let slot_b = runner.find_node_output_slot(jit_b, "value").unwrap();

        let info = PaintInformation {
            pressure: 0.5,
            ..Default::default()
        };

        let mut distinct_pairs = 0;
        let mut seen_b: Vec<f32> = Vec::new();
        for dab in 0..32 {
            runner.clear_slots();
            runner.seed_sensors(&info, [0.0; 4], 7, dab);
            runner.execute_cpu();

            let a = match runner.read_slot(slot_a).unwrap() {
                ScalarValue::Scalar(v) => v,
                _ => unreachable!(),
            };
            let b = match runner.read_slot(slot_b).unwrap() {
                ScalarValue::Scalar(v) => v,
                _ => unreachable!(),
            };

            // A has amount=0 so it must equal the input exactly.
            assert!(
                (a - 0.5).abs() < 1e-6,
                "jitter with amount=0 must pass input through, got {a}"
            );
            // B must stay within input ± amount.
            assert!(
                (0.25 - 1e-6..=0.75 + 1e-6).contains(&b),
                "jitter with input=0.5 amount=0.25 out of bounds: {b}"
            );

            // Independence from A's stream — A is constant 0.5 so this
            // collapses to "B varies." Check B varies across dabs.
            if let Some(&prev_b) = seen_b.last() {
                if (b - prev_b).abs() > 1e-6 {
                    distinct_pairs += 1;
                }
            }
            seen_b.push(b);
        }
        assert!(
            distinct_pairs > 20,
            "per-dab jitter should vary most dabs, got {distinct_pairs} changes in 32 dabs"
        );
    }
}
