//! Built-in brush packs shipped with the application.
//!
//! Each pack is a YAML file under `crates/darkly/packs/` naming its display
//! identity and the brushes it holds. The build script
//! (`crates/darkly/build.rs`) embeds every `.yaml` in that directory at
//! compile time — adding a new pack is "drop a file, no code changes", the
//! same shape [`crate::brush::builtin_brushes`] already uses.
//!
//! A pack's id is its file stem and is not written inside the file: one fact,
//! one home.

use std::sync::OnceLock;

use serde::Deserialize;

use crate::brush::pack::{validate_shipped_pack, BrushId, BrushPack, PackMutability};
use crate::catalog::{Catalog, CatalogEntry};

// `BUILTIN_PACKS_YAML: &[(filename, yaml_source)]` — generated by
// `crates/darkly/build.rs` from `crates/darkly/packs/*.yaml`.
include!(concat!(env!("OUT_DIR"), "/builtin_packs_gen.rs"));

/// A shipped pack as written on disk. The id is absent — it is the file stem.
#[derive(Deserialize)]
struct PackYaml {
    name: String,
    #[serde(default)]
    description: String,
    icon: String,
    primary: String,
    secondary: String,
    /// Defaults to [`PackMutability::Locked`]: a shipped pack is fixed unless
    /// it says otherwise, so Favorites is the one file that has to declare
    /// anything.
    #[serde(default)]
    mutability: PackMutability,
    #[serde(default)]
    members: Vec<BrushId>,
}

/// Every built-in pack, in the order `build.rs` emitted them.
///
/// Parse and validation failures panic — a shipped pack failing to load is a
/// build-time bug in data we control, not a runtime error a caller can
/// recover from. This is the reasoning `builtin_brushes::parsed` states.
fn parsed() -> Vec<BrushPack> {
    BUILTIN_PACKS_YAML
        .iter()
        .map(|(filename, yaml)| {
            let stem = filename
                .strip_suffix(".yaml")
                .expect("build.rs names every embedded pack `<stem>.yaml`");
            let y: PackYaml = serde_yaml_ng::from_str(yaml)
                .unwrap_or_else(|e| panic!("invalid built-in pack '{filename}': {e}"));
            let pack = BrushPack {
                id: stem.to_string(),
                name: y.name,
                description: y.description,
                icon: y.icon,
                primary: y.primary,
                secondary: y.secondary,
                mutability: y.mutability,
                members: y.members,
            };
            validate_shipped_pack(&pack)
                .unwrap_or_else(|e| panic!("invalid built-in pack '{filename}': {e}"));
            pack
        })
        .collect()
}

/// All built-in packs, parsed from their YAML sources.
pub fn all() -> Vec<BrushPack> {
    parsed()
}

/// The shipped packs, parsed once for the process.
///
/// Every pack is embedded at compile time, so the set is fixed and a
/// process-lifetime cache is the data's real lifetime rather than an
/// approximation of it — and it is what lets a [`CatalogEntry`]'s
/// `&'static str` fields borrow strings that arrived as owned YAML values.
pub fn docs() -> &'static [BrushPack] {
    static DOCS: OnceLock<Vec<BrushPack>> = OnceLock::new();
    DOCS.get_or_init(parsed).as_slice()
}

/// Id of the catalog the shipped packs project into.
pub const CATALOG_ID: &str = "brushPacks";

/// The first shipped pack, in declared order, that lists `brush`.
///
/// The brushes catalog's grouping axis is derived through this rather than
/// stored on the brush: membership lives on the pack, and a brush may be in
/// several, so there is one stored fact projected into the export rather than
/// two facts to keep in agreement.
pub fn pack_of(brush: &str) -> Option<&'static BrushPack> {
    docs().iter().find(|p| p.contains(brush))
}

/// The brush-pack catalog — every shipped pack, in declared order.
///
/// `type_id` is the YAML file stem, which is also the pack id, matching every
/// other catalog's snake_case type ids.
pub fn catalog() -> Catalog {
    Catalog::new(
        CATALOG_ID,
        "Brush Packs",
        docs()
            .iter()
            .map(|pack| {
                CatalogEntry::new(pack.id.as_str(), pack.name.as_str())
                    .with_description(pack.description.as_str())
                    .with_icon(pack.icon.as_str())
                    // A pack has nothing to render: it is a grouping, and its
                    // brushes carry their own previews.
                    .with_supports_preview(false)
            })
            .collect(),
    )
    .with_description(
        "The brush packs Darkly ships with. A pack groups brushes by the medium \
         they imitate; a brush may appear in several, and copying one into a pack \
         never removes it from another.",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_shipped_pack_parses() {
        let packs = all();
        assert_eq!(
            packs.len(),
            BUILTIN_PACKS_YAML.len(),
            "one pack per shipped YAML file"
        );
        assert!(!packs.is_empty(), "no shipped packs found");
        for pack in &packs {
            assert!(!pack.id.is_empty(), "a shipped pack has an empty id");
            assert!(!pack.name.is_empty(), "`{}` has no name", pack.id);
            assert!(
                !pack.description.is_empty(),
                "`{}` has no description — it is published in metadata.json",
                pack.id
            );
        }
    }

    #[test]
    fn shipped_pack_ids_are_unique() {
        let mut seen: Vec<&str> = Vec::new();
        for pack in docs() {
            assert!(
                !seen.contains(&pack.id.as_str()),
                "`{}` is declared twice",
                pack.id
            );
            seen.push(&pack.id);
        }
    }

    #[test]
    fn shipped_packs_are_locked_except_favorites() {
        // The immutability rule stated once, in data: Favorites is the one
        // built-in whose members the painter chooses, and no shipped pack is
        // fully editable.
        for pack in docs() {
            let expected = if pack.id == "favorites" {
                PackMutability::Members
            } else {
                PackMutability::Locked
            };
            assert_eq!(pack.mutability, expected, "`{}` mutability", pack.id);
        }
    }

    #[test]
    fn favorites_ships_empty() {
        let favorites = docs()
            .iter()
            .find(|p| p.id == "favorites")
            .expect("a Favorites pack ships");
        assert!(
            favorites.members.is_empty(),
            "Favorites is the painter's to fill"
        );
    }

    #[test]
    fn every_shipped_pack_icon_is_a_pack_icon() {
        // What makes a shipped pack's icon render at all: the offline icon
        // bundle is scraped from string literals in this crate, so an icon
        // named only in YAML would draw nothing.
        for pack in docs() {
            assert!(
                crate::brush::pack_icons::is_pack_icon(&pack.icon),
                "`{}` names icon `{}`, which is not in PACK_ICONS",
                pack.id,
                pack.icon
            );
        }
    }

    #[test]
    fn the_pack_catalog_covers_every_shipped_pack() {
        let catalog = catalog();
        let ids: Vec<&str> = catalog.entries.iter().map(|e| e.type_id).collect();
        let stems: Vec<&str> = docs().iter().map(|p| p.id.as_str()).collect();
        assert_eq!(ids, stems, "catalog entries must match the shipped packs");
    }

    #[test]
    fn pack_of_finds_the_first_declaring_pack() {
        // The derivation the brushes catalog's grouping axis rests on.
        let pack = pack_of("charcoal").expect("charcoal ships in a pack");
        assert_eq!(pack.id, "dry_media");
        assert!(pack_of("no_such_brush").is_none());
    }
}
