// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::brush::BrushNodeRegistration`.

pub mod circle;
pub mod curve;
pub mod image;
pub mod levels;
pub mod liquify;
pub mod multiply;
pub mod noise;
pub mod paint;
pub mod paint_color;
pub mod pen_input;
pub mod random;
pub mod smudge;
pub mod split_color;
pub mod stamp;
pub mod switch;
pub mod watercolor;

use crate::brush::BrushNodeRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<BrushNodeRegistration> {
    vec![
        circle::register(),
        curve::register(),
        image::register(),
        levels::register(),
        liquify::register(),
        multiply::register(),
        noise::register(),
        paint::register(),
        paint_color::register(),
        pen_input::register(),
        random::register(),
        smudge::register(),
        split_color::register(),
        stamp::register(),
        switch::register(),
        watercolor::register(),
    ]
}
