// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::brush::BrushNodeRegistration`.

pub mod add;
pub mod circle;
pub mod clamp;
pub mod curve;
pub mod jitter;
pub mod liquify_compiled;
pub mod make_color;
pub mod mix;
pub mod multiply;
pub mod paint_color;
pub mod paint_compiled;
pub mod pen_input;
pub mod random;
pub mod remap;
pub mod scatter;
pub mod smudge_compiled;
pub mod split_vec2;
pub mod stamp;
pub mod watercolor_compiled;

use crate::brush::BrushNodeRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<BrushNodeRegistration> {
    vec![
        add::register(),
        circle::register(),
        clamp::register(),
        curve::register(),
        jitter::register(),
        liquify_compiled::register(),
        make_color::register(),
        mix::register(),
        multiply::register(),
        paint_color::register(),
        paint_compiled::register(),
        pen_input::register(),
        random::register(),
        remap::register(),
        scatter::register(),
        smudge_compiled::register(),
        split_vec2::register(),
        stamp::register(),
        watercolor_compiled::register(),
    ]
}
