// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::gpu::filter::FilterRegistration`.

pub mod noise;

use crate::gpu::filter::FilterRegistration;

pub fn registrations() -> Vec<FilterRegistration> {
    vec![
        noise::register(),
    ]
}
