// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::gpu::filter::FilterPipelineRegistration`.

pub mod curves;
pub mod hsv;
pub mod invert;
pub mod levels;

use crate::gpu::filter::FilterPipelineRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<FilterPipelineRegistration> {
    vec![
        curves::register(),
        hsv::register(),
        invert::register(),
        levels::register(),
    ]
}
