// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::document::filter::FilterEntityRegistration`.

pub mod mask;
pub mod selection;

use crate::document::filter::FilterEntityRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<FilterEntityRegistration> {
    vec![
        mask::register(),
        selection::register(),
    ]
}
