// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::gpu::adjustment::AdjustmentRegistration`.

pub mod invert;

use crate::gpu::adjustment::AdjustmentRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<AdjustmentRegistration> {
    vec![
        invert::register(),
    ]
}
