use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let src = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("src");

    generate_registry(&src.join("gpu/veils"), "crate::gpu::veil::VeilRegistration");

    generate_registry(&src.join("tools"), "crate::tool::ToolRegistration");

    generate_registry(
        &src.join("brush/nodes"),
        "crate::brush::BrushNodeRegistration",
    );

    generate_registry(
        &src.join("brush/stabilizers"),
        "crate::brush::stabilizer::StabilizerRegistration",
    );
}

/// Scan a directory for .rs module files (excluding mod.rs) and generate
/// a mod.rs that re-exports all modules and provides a `registrations()`
/// function collecting each module's `register()` return value.
///
/// Convention: each module must export
///   `pub fn register() -> {registration_type}`
///
/// This is the Rust equivalent of Python's __init__.py auto-discovery:
/// drop a new .rs file in the directory, it gets picked up automatically.
fn generate_registry(dir: &Path, registration_type: &str) {
    let mut modules = Vec::new();

    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "rs") {
                let stem = path.file_stem().unwrap().to_str().unwrap().to_string();
                if stem != "mod" {
                    modules.push(stem);
                }
            }
        }
    }

    modules.sort();

    // Extract just the struct name from the full path for use in fn signature.
    // e.g. "crate::gpu::filter::FilterRegistration" -> "FilterRegistration"
    let type_name = registration_type.rsplit("::").next().unwrap();

    let mut code = String::new();
    code.push_str("// @generated by build.rs — do not edit manually.\n");
    code.push_str("// To add a new module, create a .rs file in this directory\n");
    code.push_str(&format!(
        "// that exports `pub fn register() -> {registration_type}`.\n\n"
    ));

    for m in &modules {
        code.push_str(&format!("pub mod {m};\n"));
    }

    code.push_str(&format!("\nuse {registration_type};\n\n"));
    // Skip rustfmt on the generated body — layout varies across rustfmt
    // versions (single-element `vec![]` collapses on newer versions),
    // which would otherwise make CI's fmt check depend on the toolchain.
    code.push_str("#[rustfmt::skip]\n");
    code.push_str(&format!("pub fn registrations() -> Vec<{type_name}> {{\n"));
    code.push_str("    vec![\n");
    for m in &modules {
        code.push_str(&format!("        {m}::register(),\n"));
    }
    code.push_str("    ]\n");
    code.push_str("}\n");

    let mod_path = dir.join("mod.rs");
    let existing = fs::read_to_string(&mod_path).unwrap_or_default();
    if existing != code {
        fs::write(&mod_path, code).unwrap();
    }

    println!("cargo:rerun-if-changed={}", dir.display());
}
