<!--
  The single icon surface for the app. Renders a registered Iconify icon
  fully offline — `generateIcon` only reads the locally-registered collections
  (see ./bundle.generated, regenerated by `npm run gen:icons`); there is no API
  client in the import graph, so a render can never hit the network.

  We inline @iconify/svelte's OfflineIcon render (generateIcon + {@html}) rather
  than importing its `.svelte` component: the package exports that component
  only under the `svelte` condition, which Vite's dependency *scanner* doesn't
  apply, so importing it breaks `vite dev`. The functions entry resolves cleanly.

  Call sites pass a full Iconify name, e.g. <Icon name="fa6-solid:eye" />.
  `inline` is on by default so the SVG sits on the text baseline the way the old
  Font Awesome <i> glyphs did (Iconify emits vertical-align: -0.125em).
-->
<script lang="ts">
    import { generateIcon } from '@iconify/svelte/dist/offline-functions.js';
    import './bundle.generated'; // side effect: registers the offline collections

    interface Props {
        name: string;
        class?: string;
        inline?: boolean;
        [key: `data-${string}`]: string;
    }

    let { name, class: cls = '', inline = true, ...rest }: Props = $props();

    const data = $derived.by(() => {
        const props: Record<string, unknown> = {
            icon: name,
            inline,
            width: '1em',
            height: '1em',
            'aria-hidden': 'true',
            ...rest,
        };
        if (cls) props.class = cls;
        return generateIcon(props as unknown as Parameters<typeof generateIcon>[0]);
    });

    // Catch-all for nonexistent / mistyped names that slip past the build-time
    // generator (e.g. an unknown prefix) — surfaced loudly in dev so a blank
    // icon never goes unnoticed.
    $effect(() => {
        if (!data && import.meta.env.DEV) {
            console.warn(
                `[Icon] "${name}" is not in the offline bundle — check the name/prefix, then run \`npm run gen:icons\`.`,
            );
        }
    });
</script>

{#if data?.svg}
    <svg {...data.attributes}>{@html data.body}</svg>
{:else if data}
    <span {...data.attributes}></span>
{/if}
