// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::gpu::veil::VeilRegistration`.

pub mod bokeh;
pub mod kuwahara;
pub mod monochrome;
pub mod noise;
pub mod pixelate;
pub mod rainy_glass;
pub mod watercolor;

use crate::gpu::veil::VeilRegistration;

pub fn registrations() -> Vec<VeilRegistration> {
    vec![
        bokeh::register(),
        kuwahara::register(),
        monochrome::register(),
        noise::register(),
        pixelate::register(),
        rainy_glass::register(),
        watercolor::register(),
    ]
}
