// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::gpu::veil::VeilRegistration`.

pub mod frozen;
pub mod grain;
pub mod lens_blur;
pub mod monochrome;
pub mod painting;
pub mod pixelate;
pub mod rainy_glass;
pub mod vhs;
pub mod watercolor;

use crate::gpu::veil::VeilRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<VeilRegistration> {
    vec![
        frozen::register(),
        grain::register(),
        lens_blur::register(),
        monochrome::register(),
        painting::register(),
        pixelate::register(),
        rainy_glass::register(),
        vhs::register(),
        watercolor::register(),
    ]
}
