// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::gpu::blend_mode::BlendModeRegistration`.

pub mod color;
pub mod color_burn;
pub mod color_dodge;
pub mod darken;
pub mod difference;
pub mod hard_light;
pub mod hue;
pub mod lighten;
pub mod linear_dodge;
pub mod luminosity;
pub mod multiply;
pub mod normal;
pub mod overlay;
pub mod saturation;
pub mod screen;
pub mod soft_light;

use crate::gpu::blend_mode::BlendModeRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<BlendModeRegistration> {
    vec![
        color::register(),
        color_burn::register(),
        color_dodge::register(),
        darken::register(),
        difference::register(),
        hard_light::register(),
        hue::register(),
        lighten::register(),
        linear_dodge::register(),
        luminosity::register(),
        multiply::register(),
        normal::register(),
        overlay::register(),
        saturation::register(),
        screen::register(),
        soft_light::register(),
    ]
}
