// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::action::ActionCategory`.

pub mod brush;
pub mod colors;
pub mod edit;
pub mod file;
pub mod layers;
pub mod selection;
pub mod tools;
pub mod transform;
pub mod view;

use crate::action::ActionCategory;

#[rustfmt::skip]
pub fn registrations() -> Vec<ActionCategory> {
    vec![
        brush::register(),
        colors::register(),
        edit::register(),
        file::register(),
        layers::register(),
        selection::register(),
        tools::register(),
        transform::register(),
        view::register(),
    ]
}
