// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::gpu::void::VoidRegistration`.

pub mod blender;
pub mod camera;
pub mod noise;
pub mod screenshare;
pub mod smart_object;

use crate::gpu::void::VoidRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<VoidRegistration> {
    vec![
        blender::register(),
        camera::register(),
        noise::register(),
        screenshare::register(),
        smart_object::register(),
    ]
}
