// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::gpu::void::VoidRegistration`.

pub mod noise;

use crate::gpu::void::VoidRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<VoidRegistration> {
    vec![
        noise::register(),
    ]
}
