// @generated by build.rs: do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::docs_md::FragmentRegistration`.

pub mod catalog_graphic;
pub mod catalog_table;

use crate::docs_md::FragmentRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<FragmentRegistration> {
    vec![
        catalog_graphic::register(),
        catalog_table::register(),
    ]
}
