//! The one shape every registry of typed variants projects into.
//!
//! Filters, veils, voids, blend modes, tools, layer kinds and layer filters all
//! answer the same questions — what is this variant called, what does it look
//! like, what does it do, what can you set on it — and each used to answer them
//! through its own flat `*TypeInfo` struct and its own engine query. This module
//! replaces all of them with [`Catalog`] and [`CatalogEntry`].
//!
//! Each registration type builds its own [`CatalogEntry`] in its own file, so
//! nothing here branches on which registry it is looking at and adding a veil
//! touches nothing outside `gpu/veils/`. The enumeration of catalog-producing
//! registries is generated by `build.rs` from the module directories it scans,
//! so a registry cannot be silently left out of the projection.

use crate::config::schema::WidgetHint;
use crate::engine::types::ParamInfo;
use crate::gpu::void::CaptureKind;

/// One browsable entry in a registry of typed variants — the single shape the
/// UI pickers, the settings surface and the metadata export all consume.
#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]
pub struct CatalogEntry {
    #[serde(rename = "type")]
    pub type_id: &'static str,
    pub display_name: &'static str,
    /// Iconify name, or `None` when the variant deliberately declares no icon
    /// (veils render a live preview; raster layers always show a thumbnail).
    pub icon: Option<&'static str>,
    pub description: Option<&'static str>,
    /// Grouping label within the catalog, for variants that group.
    pub category: Option<&'static str>,
    /// Action id this variant is bound to, for variants a hotkey can select.
    pub hotkey_action: Option<&'static str>,
    pub params: Vec<ParamInfo>,
    /// Whether this variant declares a
    /// [`PreviewAnim`](crate::gpu::preview::PreviewAnim) — the one fact behind
    /// "a rendered preview of it exists". False for the registries whose entries
    /// are affordances rather than images.
    ///
    /// It does **not** promise a *picker* preview. A blend mode declares one and
    /// has a documentation asset, but is a relation between two images rather
    /// than an effect over one, so its catalog exports no preview mechanism and
    /// `start_preview` no-ops for it exactly as it does for an unknown type.
    /// Whether a catalog can be driven live is
    /// [`preview_mechanisms`](crate::catalog::preview_mechanisms)' answer, not
    /// this field's.
    pub supports_preview: bool,
    /// How the browser captures this variant's external frames; voids only.
    pub capture_kind: Option<CaptureKind>,
}

impl CatalogEntry {
    /// An entry carrying only the fields every registry has. Registries layer
    /// their own metadata on with the `with_*` setters, so a registry that has
    /// no icon or no parameters says so by staying silent rather than by
    /// spelling out a row of `None`s.
    pub fn new(type_id: &'static str, display_name: &'static str) -> Self {
        CatalogEntry {
            type_id,
            display_name,
            icon: None,
            description: None,
            category: None,
            hotkey_action: None,
            params: Vec::new(),
            supports_preview: false,
            capture_kind: None,
        }
    }

    /// Set the Iconify name, treating `""` as "declares no icon". Registries
    /// that store a non-optional `&'static str` use the empty string for that,
    /// and this is the one place that convention is translated.
    pub fn with_icon(mut self, icon: &'static str) -> Self {
        self.icon = (!icon.is_empty()).then_some(icon);
        self
    }

    pub fn with_description(mut self, description: &'static str) -> Self {
        self.description = (!description.is_empty()).then_some(description);
        self
    }

    pub fn with_category(mut self, category: &'static str) -> Self {
        self.category = (!category.is_empty()).then_some(category);
        self
    }

    pub fn with_hotkey_action(mut self, action: &'static str) -> Self {
        self.hotkey_action = (!action.is_empty()).then_some(action);
        self
    }

    pub fn with_params(mut self, params: &'static [crate::gpu::params::ParamDef]) -> Self {
        self.params = params
            .iter()
            .map(|d| ParamInfo::from_def(d, None))
            .collect();
        self
    }

    pub fn with_supports_preview(mut self, supports_preview: bool) -> Self {
        self.supports_preview = supports_preview;
        self
    }

    pub fn with_capture_kind(mut self, capture_kind: Option<CaptureKind>) -> Self {
        self.capture_kind = capture_kind;
        self
    }
}

/// A named group of entries — "filters", "veils", "settings.canvas", …
#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]
pub struct Catalog {
    pub id: &'static str,
    pub title: &'static str,
    pub description: Option<&'static str>,
    pub icon: Option<&'static str>,
    /// Presentation order, for catalogs that declare one. Registry catalogs do
    /// not; settings sections do.
    pub order: Option<i32>,
    pub entries: Vec<CatalogEntry>,
    /// Whether an entry's icon identifies it within the catalog.
    ///
    /// True for the registries whose entries are picker variants, where the
    /// glyph is most of what the user has to tell two of them apart and a
    /// duplicate is a copy-pasted `register()` that kept the donor's. Actions
    /// declare it false: an action's glyph depicts the *operation*, so the same
    /// operation at another scope wants the same glyph (flipping the canvas and
    /// flipping a layer are both `arrows-left-right`), and an action is never
    /// shown without its label.
    ///
    /// Says how to read the icons rather than what they are, so it stays out of
    /// the exported artifact.
    #[serde(skip)]
    #[cfg_attr(feature = "ts-export", ts(skip))]
    pub icons_identify_entries: bool,
}

impl Catalog {
    pub fn new(id: &'static str, title: &'static str, entries: Vec<CatalogEntry>) -> Self {
        Catalog {
            id,
            title,
            description: None,
            icon: None,
            order: None,
            entries,
            icons_identify_entries: true,
        }
    }

    /// Declare that entries in this catalog may share a glyph — see
    /// [`Catalog::icons_identify_entries`].
    pub fn with_shared_icons(mut self) -> Self {
        self.icons_identify_entries = false;
        self
    }

    pub fn with_description(mut self, description: &'static str) -> Self {
        self.description = (!description.is_empty()).then_some(description);
        self
    }

    pub fn with_icon(mut self, icon: &'static str) -> Self {
        self.icon = (!icon.is_empty()).then_some(icon);
        self
    }

    pub fn with_order(mut self, order: i32) -> Self {
        self.order = Some(order);
        self
    }
}

include!(concat!(env!("OUT_DIR"), "/catalog_sources_gen.rs"));

/// Every settings section, projected into the same shape as a registry.
///
/// One catalog per section, one entry per section, one [`ParamInfo`] per pref —
/// so a consumer that can render a filter's parameter table can render the
/// settings surface with no second code path. Ids are prefixed `settings.`,
/// which cannot collide with a registry catalog id because none contains a dot.
///
/// Prefs declaring [`WidgetHint::Hidden`] are excluded: panel visibility, the
/// recent-files list and friends ride the same persistence pipe as real
/// settings but are not settings, and the live UI already skips them. Applying
/// the rule here keeps it in one place rather than leaving it to each consumer.
pub fn settings_catalogs() -> Vec<Catalog> {
    let mut out: Vec<(i32, &'static str, Catalog)> = crate::config::sections::registrations()
        .iter()
        .map(|section| {
            let params: Vec<ParamInfo> = section
                .prefs
                .iter()
                .filter(|p| !matches!(p.widget, WidgetHint::Hidden))
                .map(ParamInfo::from_pref)
                .collect();
            let entry = CatalogEntry {
                type_id: section.id,
                display_name: section.display_name,
                icon: section.icon,
                description: section.description,
                category: None,
                hotkey_action: None,
                params,
                supports_preview: false,
                capture_kind: None,
            };
            let mut catalog = Catalog::new(
                // `id` must be `'static`; sections are `'static` data, so lean
                // on the same leak-free trick the registries do — the section's
                // own id with a compile-time-known prefix, built once.
                settings_catalog_id(section.id),
                section.display_name,
                vec![entry],
            )
            .with_order(section.order);
            if let Some(d) = section.description {
                catalog = catalog.with_description(d);
            }
            if let Some(i) = section.icon {
                catalog = catalog.with_icon(i);
            }
            (section.order, section.id, catalog)
        })
        .collect();
    out.sort_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.cmp(b.1)));
    out.into_iter().map(|(_, _, c)| c).collect()
}

/// `"settings.<id>"` as a `&'static str`. Sections are a fixed, compile-time
/// set discovered by `build.rs`, so the ids are interned once for the process
/// rather than rebuilt per call.
fn settings_catalog_id(section_id: &'static str) -> &'static str {
    use std::collections::HashMap;
    use std::sync::{Mutex, OnceLock};
    static IDS: OnceLock<Mutex<HashMap<&'static str, &'static str>>> = OnceLock::new();
    let mut map = IDS
        .get_or_init(|| Mutex::new(HashMap::new()))
        .lock()
        .expect("settings id cache poisoned");
    map.entry(section_id)
        .or_insert_with(|| Box::leak(format!("settings.{section_id}").into_boxed_str()))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Nothing ships undocumented: every catalog names and describes itself,
    /// and so does every entry in it.
    ///
    /// `icon`, `category` and `hotkey_action` are deliberately *not* asserted.
    /// `None` on those is a declared value rather than a missing one — veils
    /// render a live preview instead of an icon, raster layers always show a
    /// thumbnail, and only tools bind a hotkey — which is the whole reason they
    /// are `Option` rather than `&'static str`. Demanding them back would be a
    /// rule the data does not have. Malformed icons are caught by
    /// [`icons_are_wellformed_and_unique_within_a_catalog`] instead.
    #[test]
    fn every_catalog_entry_is_documented() {
        for cat in catalogs() {
            assert!(!cat.id.is_empty(), "catalog has an empty id");
            assert!(!cat.title.is_empty(), "catalog `{}` has no title", cat.id);
            assert!(
                cat.description.is_some_and(|d| !d.is_empty()),
                "catalog `{}` has no description",
                cat.id
            );
            assert!(
                !cat.entries.is_empty(),
                "catalog `{}` has no entries",
                cat.id
            );

            for e in &cat.entries {
                assert!(
                    !e.type_id.is_empty(),
                    "an entry in `{}` has an empty type id",
                    cat.id
                );
                assert!(
                    !e.display_name.is_empty(),
                    "`{}/{}` has no display name",
                    cat.id,
                    e.type_id
                );
                assert!(
                    e.description.is_some_and(|d| !d.is_empty()),
                    "`{}/{}` has no description",
                    cat.id,
                    e.type_id
                );
            }
        }
    }

    /// Generalizes the per-registry uniqueness check `gpu/filter.rs` used to
    /// carry: a copy-pasted `register()` that kept the donor's glyph shows up
    /// as two entries in one catalog claiming the same icon. Catalogs whose
    /// glyphs are not identifying opt out of the uniqueness half — see
    /// [`Catalog::icons_identify_entries`] — but not the wellformedness half.
    #[test]
    fn icons_are_wellformed_and_unique_within_a_catalog() {
        for cat in catalogs() {
            let mut seen: Vec<(&str, &str)> = Vec::new();
            for e in &cat.entries {
                let Some(icon) = e.icon else { continue };
                assert!(
                    icon.contains(':'),
                    "`{}/{}` icon `{icon}` is not a `collection:name` Iconify id",
                    cat.id,
                    e.type_id
                );
                assert!(
                    !icon.ends_with(':') && !icon.starts_with(':'),
                    "`{}/{}` icon `{icon}` has an empty collection or name",
                    cat.id,
                    e.type_id
                );
                if !cat.icons_identify_entries {
                    continue;
                }
                if let Some((owner, _)) = seen.iter().find(|(_, i)| *i == icon) {
                    panic!(
                        "`{}/{}` and `{}/{}` both use icon `{icon}`",
                        cat.id, owner, cat.id, e.type_id
                    );
                }
                seen.push((e.type_id, icon));
            }
        }
    }

    /// Settings project on the same footing as a registry: one catalog per
    /// section, `settings.`-prefixed so it cannot collide with a registry id,
    /// and carrying only prefs that are actually settings.
    #[test]
    fn settings_project_as_catalogs_without_hidden_prefs() {
        let cats = settings_catalogs();
        assert!(!cats.is_empty(), "no settings sections found");

        let declared: usize = crate::config::sections::registrations()
            .iter()
            .map(|s| s.prefs.len())
            .sum();
        let hidden: usize = crate::config::sections::registrations()
            .iter()
            .flat_map(|s| s.prefs.iter())
            .filter(|p| matches!(p.widget, WidgetHint::Hidden))
            .count();
        let exported: usize = cats
            .iter()
            .flat_map(|c| &c.entries)
            .map(|e| e.params.len())
            .sum();
        assert!(
            hidden > 0,
            "expected some hidden prefs to exercise the filter"
        );
        assert_eq!(
            exported,
            declared - hidden,
            "settings export must carry every declared pref except the hidden ones"
        );

        for c in &cats {
            assert!(
                c.id.starts_with("settings."),
                "`{}` is not settings-prefixed",
                c.id
            );
            assert!(
                c.order.is_some(),
                "settings catalog `{}` declares no order",
                c.id
            );
            assert_eq!(
                c.entries.len(),
                1,
                "`{}` should hold exactly one entry",
                c.id
            );
            for p in &c.entries[0].params {
                assert_ne!(p.widget, "hidden", "`{}` exported a hidden pref", c.id);
            }
        }

        // Settings ids and registry ids share one namespace and must not collide.
        for r in catalogs() {
            assert!(
                !r.id.contains('.'),
                "registry catalog `{}` contains a dot",
                r.id
            );
        }
    }

    #[test]
    fn catalog_ids_and_entry_ids_are_unique_and_stable() {
        let cats = catalogs();
        let mut ids: Vec<&str> = cats.iter().map(|c| c.id).collect();
        ids.sort_unstable();
        let before = ids.len();
        ids.dedup();
        assert_eq!(before, ids.len(), "two catalogs claim the same id");

        for cat in &cats {
            let mut entry_ids: Vec<&str> = cat.entries.iter().map(|e| e.type_id).collect();
            entry_ids.sort_unstable();
            let before = entry_ids.len();
            entry_ids.dedup();
            assert_eq!(
                before,
                entry_ids.len(),
                "two entries in catalog `{}` claim the same type id",
                cat.id
            );
        }

        // Entry order is part of the contract — a caller that renders a catalog
        // twice must get the same table both times.
        for cat in &cats {
            let rebuilt = catalogs();
            let same = rebuilt.iter().find(|c| c.id == cat.id).unwrap();
            let a: Vec<&str> = cat.entries.iter().map(|e| e.type_id).collect();
            let b: Vec<&str> = same.entries.iter().map(|e| e.type_id).collect();
            assert_eq!(a, b, "catalog `{}` is not order-stable", cat.id);
        }
    }
}
