// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::gpu::effect::EffectRegistration`.

pub mod black_and_white;
pub mod brightness_contrast;
pub mod chromatic_aberration;
pub mod curves;
pub mod frozen;
pub mod grain;
pub mod hsv;
pub mod invert;
pub mod lens_blur;
pub mod levels;
pub mod painting;
pub mod pixelate;
pub mod rainy_glass;
pub mod vhs;

use crate::gpu::effect::EffectRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<EffectRegistration> {
    vec![
        black_and_white::register(),
        brightness_contrast::register(),
        chromatic_aberration::register(),
        curves::register(),
        frozen::register(),
        grain::register(),
        hsv::register(),
        invert::register(),
        lens_blur::register(),
        levels::register(),
        painting::register(),
        pixelate::register(),
        rainy_glass::register(),
        vhs::register(),
    ]
}
