// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::brush::stabilizer::StabilizerRegistration`.

pub mod laplacian;

use crate::brush::stabilizer::StabilizerRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<StabilizerRegistration> {
    vec![
        laplacian::register(),
    ]
}
