// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::tool::ToolRegistration`.

pub mod brush;
pub mod colorpicker;
pub mod ellipse_select;
pub mod fill;
pub mod gradient;
pub mod lasso_select;
pub mod magic_wand;
pub mod polygon_select;
pub mod rect_select;
pub mod transform;

use crate::tool::ToolRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<ToolRegistration> {
    vec![
        brush::register(),
        colorpicker::register(),
        ellipse_select::register(),
        fill::register(),
        gradient::register(),
        lasso_select::register(),
        magic_wand::register(),
        polygon_select::register(),
        rect_select::register(),
        transform::register(),
    ]
}
