import { toolRegistry } from './registry';
import { brushTool } from './brush.svelte';
import { eraserTool } from './eraser.svelte';
import { fillTool } from './fill.svelte';
import { gradientTool } from './gradient.svelte';
import { colorPickerTool } from './colorpicker.svelte';
import { rectSelectTool } from './rect_select.svelte';
import { ellipseSelectTool } from './ellipse_select.svelte';
import { lassoSelectTool } from './lasso_select.svelte';
import { magicWandTool } from './magic_wand.svelte';
import { transformTool } from './transform.svelte';
import { overlayPreviewTool } from './overlay_preview.svelte';

toolRegistry.register(brushTool);
toolRegistry.register(eraserTool);
toolRegistry.register(fillTool);
toolRegistry.register(gradientTool);
toolRegistry.register(colorPickerTool);
toolRegistry.register(rectSelectTool);
toolRegistry.register(ellipseSelectTool);
toolRegistry.register(lassoSelectTool);
toolRegistry.register(magicWandTool);
toolRegistry.register(transformTool);
toolRegistry.register(overlayPreviewTool);
