// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::config::schema::SchemaSection`.

pub mod animation;
pub mod app;
pub mod autosave;
pub mod canvas;
pub mod colors;
pub mod display;
pub mod edit;
pub mod input;
pub mod nav;
pub mod recording;
pub mod rendering;
pub mod tools;
pub mod ui;

use crate::config::schema::SchemaSection;

#[rustfmt::skip]
pub fn registrations() -> Vec<SchemaSection> {
    vec![
        animation::register(),
        app::register(),
        autosave::register(),
        canvas::register(),
        colors::register(),
        display::register(),
        edit::register(),
        input::register(),
        nav::register(),
        recording::register(),
        rendering::register(),
        tools::register(),
        ui::register(),
    ]
}
