// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::document::modifier::ModifierRegistration`.

pub mod mask;

use crate::document::modifier::ModifierRegistration;

#[rustfmt::skip]
pub fn registrations() -> Vec<ModifierRegistration> {
    vec![
        mask::register(),
    ]
}
