// @generated by build.rs — do not edit manually.
// To add a new module, create a .rs file in this directory
// that exports `pub fn register() -> crate::config::schema::Preset`.

pub mod gimp;
pub mod krita;
pub mod photoshop;

use crate::config::schema::Preset;

#[rustfmt::skip]
pub fn registrations() -> Vec<Preset> {
    vec![
        gimp::register(),
        krita::register(),
        photoshop::register(),
    ]
}
